name: Update Sheet Data

on:
  schedule:
    - cron: "0 6,15 * * *" # Runs at 6 AM and 3 PM UTC (2 PM and 11 PM Singapore time)
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main
      - dev

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Run update script
        run: node updateSheetData.js
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add products.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update products data" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}