name: Update Sheet Data

on:
  schedule:
    - cron: "0 6,15 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Run update script
        env:
          WHOLE_LIST_SHEET_URL: ${{ secrets.WHOLE_LIST_SHEET_URL }}
          FRUITS_LIST_SHEET_URL: ${{ secrets.FRUITS_LIST_SHEET_URL }}
        run: node updateSheetData.js
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add "whole list/products.json" "fruits list/products.json"
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update products data" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
